// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYStvnXx9vel-uQvstPx7nxUpS4PrsdTQ',
    appId: '1:901828986581:web:5b738da36592481db1c45c',
    messagingSenderId: '901828986581',
    projectId: 'bicolanofolkdance-edb41',
    authDomain: 'bicolanofolkdance-edb41.firebaseapp.com',
    storageBucket: 'bicolanofolkdance-edb41.appspot.com',
    measurementId: 'G-GWFQWHP64X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPRbtm9QmS-OK7G8pY3Pr7-NLzMMwdf7o',
    appId: '1:901828986581:android:2d7ed2b9e2d04d97b1c45c',
    messagingSenderId: '901828986581',
    projectId: 'bicolanofolkdance-edb41',
    storageBucket: 'bicolanofolkdance-edb41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfSoVSfFR_6h1JvmJBR6NPkgtEC3adiYs',
    appId: '1:901828986581:ios:4d18eb34e5ee05e7b1c45c',
    messagingSenderId: '901828986581',
    projectId: 'bicolanofolkdance-edb41',
    storageBucket: 'bicolanofolkdance-edb41.appspot.com',
    iosBundleId: 'com.example.bicolFolkdance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYStvnXx9vel-uQvstPx7nxUpS4PrsdTQ',
    appId: '1:901828986581:web:00ac529008d3d8d1b1c45c',
    messagingSenderId: '901828986581',
    projectId: 'bicolanofolkdance-edb41',
    authDomain: 'bicolanofolkdance-edb41.firebaseapp.com',
    storageBucket: 'bicolanofolkdance-edb41.appspot.com',
    measurementId: 'G-DQ9NCCVL3W',
  );
}
